version: "3.9"

services:
  register-blocks:
    image: ghcr.io/herugen/stevedore-downloader:latest
    build:
      context: ..
      dockerfile: docker/download-worker/Dockerfile
    command: python scripts/register_local_blocks.py
    env_file:
      - ../profiles/local.env
    restart: "no"

  apply-deployment:
    image: ghcr.io/herugen/stevedore-downloader:latest
    build:
      context: ..
      dockerfile: docker/download-worker/Dockerfile
    command: python deployments/local_download_worker.py
    env_file:
      - ../profiles/local.env
    depends_on:
      register-blocks:
        condition: service_completed_successfully
    restart: "no"

  downloader:
    image: ghcr.io/herugen/stevedore-downloader:latest
    build:
      context: ..
      dockerfile: docker/download-worker/Dockerfile
    env_file:
      - ../profiles/local.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

