name: Build and Push Download Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stevedore-downloader
            dockerfile: docker/download-worker/Dockerfile
            context: .
            tags: ghcr.io/${{ github.repository }}/stevedore-downloader:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tags }}
          cache-from: type=registry,ref=${{ matrix.tags }}
          cache-to: type=inline

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io

